apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dba-toolbox.fullname" . }}
  labels:
    {{- include "dba-toolbox.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "dba-toolbox.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: OrderedReady
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dba-toolbox.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "dba-toolbox.labels" . | nindent 8 }}
      annotations:
        checksum/connections: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum | quote }}
        checksum/extra-objects: {{ toYaml .Values.extraObjects | sha256sum | quote }}
        checksum/ca-bundle: {{ .Values.caBundle | sha256sum | quote }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: toolbox
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: HOME
              value: {{ printf "%s/home" .Values.persistence.config.mountPath | quote }}
            - name: MC_CONFIG_DIR
              value: {{ printf "%s/mc" .Values.persistence.config.mountPath | quote }}
            - name: PGSERVICEFILE
              value: {{ printf "%s/home/.pg_service.conf" .Values.persistence.config.mountPath | quote }}
            - name: PGPASSFILE
              value: {{ printf "%s/home/.pgpass" .Values.persistence.config.mountPath | quote }}
            - name: S3_BUCKETS_FILE
              value: {{ printf "%s/home/.s3-buckets" .Values.persistence.config.mountPath | quote }}
            {{- if .Values.caBundle }}
            - name: SSL_CERT_FILE
              value: /etc/ssl/custom/ca-bundle.crt
            - name: PGSSLROOTCERT
              value: /etc/ssl/custom/ca-bundle.crt
            {{- end }}
            {{- $root := . }}
            {{- range $index, $name := keys .Values.connections.minio | sortAlpha }}
            {{- $connection := index $root.Values.connections.minio $name }}
            {{- if $connection.existingSecret.name }}
            - name: MINIO_{{ $index }}_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ $connection.existingSecret.name | quote }}
                  key: {{ default "endpoint" $connection.existingSecret.endpointKey | quote }}
            - name: MINIO_{{ $index }}_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $connection.existingSecret.name | quote }}
                  key: {{ default "accessKey" $connection.existingSecret.accessKeyKey | quote }}
            - name: MINIO_{{ $index }}_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $connection.existingSecret.name | quote }}
                  key: {{ default "secretKey" $connection.existingSecret.secretKeyKey | quote }}
            - name: MINIO_{{ $index }}_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ $connection.existingSecret.name | quote }}
                  key: {{ default "bucket" $connection.existingSecret.bucketKey | quote }}
            {{- end }}
            {{- end }}
            {{- range $index, $name := keys .Values.connections.postgres | sortAlpha }}
            {{- $connection := index $root.Values.connections.postgres $name }}
            {{- if $connection.existingSecret.name }}
            {{- with $connection.existingSecret.hostKey }}
            - name: POSTGRES_{{ $index }}_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ $connection.existingSecret.name | quote }}
                  key: {{ . | quote }}
            {{- end }}
            {{- if not $connection.existingSecret.connectingStringKey }}
            - name: POSTGRES_{{ $index }}_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ $connection.existingSecret.name | quote }}
                  key: {{ default "database" $connection.existingSecret.databaseKey | quote }}
            - name: POSTGRES_{{ $index }}_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $connection.existingSecret.name | quote }}
                  key: {{ default "username" $connection.existingSecret.userKey | quote }}
            - name: POSTGRES_{{ $index }}_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $connection.existingSecret.name | quote }}
                  key: {{ default "password" $connection.existingSecret.passwordKey | quote }}
            {{- end }}
            {{- with $connection.existingSecret.connectingStringKey }}
            - name: POSTGRES_{{ $index }}_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ $connection.existingSecret.name | quote }}
                  key: {{ . | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ printf "%s-connections" (include "dba-toolbox.fullname" .) }}
          volumeMounts:
            - name: toolbox-work
              mountPath: {{ .Values.persistence.work.mountPath }}
            - name: toolbox-config
              mountPath: {{ .Values.persistence.config.mountPath }}
            {{- if .Values.caBundle }}
            - name: custom-ca
              mountPath: /etc/ssl/custom
              readOnly: true
            - name: custom-ca
              mountPath: {{ printf "%s/mc/certs/CAs" .Values.persistence.config.mountPath }}
              readOnly: true
            {{- end }}
            - name: tmp
              mountPath: /tmp
      volumes:
        {{- if not .Values.persistence.work.enabled }}
        - name: toolbox-work
          emptyDir: {}
        {{- end }}
        {{- if not .Values.persistence.config.enabled }}
        - name: toolbox-config
          emptyDir: {}
        {{- end }}
        - name: tmp
          emptyDir: {}
        {{- if .Values.caBundle }}
        - name: custom-ca
          configMap:
            name: {{ include "dba-toolbox.fullname" . }}-ca-bundle
            items:
              - key: ca-bundle.crt
                path: ca-bundle.crt
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if or .Values.persistence.work.enabled .Values.persistence.config.enabled }}
  volumeClaimTemplates:
    {{- if .Values.persistence.work.enabled }}
    - metadata:
        name: toolbox-work
      spec:
        accessModes:
          {{- toYaml .Values.persistence.work.accessModes | nindent 10 }}
        {{- with .Values.persistence.work.storageClassName }}
        storageClassName: {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.work.size | quote }}
    {{- end }}
    {{- if .Values.persistence.config.enabled }}
    - metadata:
        name: toolbox-config
      spec:
        accessModes:
          {{- toYaml .Values.persistence.config.accessModes | nindent 10 }}
        {{- with .Values.persistence.config.storageClassName }}
        storageClassName: {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.config.size | quote }}
    {{- end }}
  {{- end }}
